SELECT 
    ROUND(
        ABS(MIN_LAT_N - MAX_LAT_N) + ABS(MIN_LONG_W - MAX_LONG_W), 
        4
    ) AS MANHATTAN_DISTANCE
FROM (
    SELECT 
        (SELECT MIN(LAT_N) FROM STATION) AS MIN_LAT_N,
        (SELECT MIN(LONG_W) FROM STATION) AS MIN_LONG_W,
        (SELECT MAX(LAT_N) FROM STATION) AS MAX_LAT_N,
        (SELECT MAX(LONG_W) FROM STATION) AS MAX_LONG_W
) sub;